{% set version = "0.4.33.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-runit
  version: {{ version|replace("-", "_") }}

source:
  fn: RUnit_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RUnit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RUnit/RUnit_{{ version }}.tar.gz
  sha256: 8528fa3ba8d04a6e71783f01ba3e1163b5900c6b3c2bc81bad2349e220197f05

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RUnit')"           # [not win]
    - "\"%R%\" -e \"library('RUnit')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RUnit
  license: GPL-2
  summary: R functions implementing a standard Unit Testing framework, with additional code inspection and report generation tools.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
