appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Px9wg4oJmOsVkp+mL57NZEMaar/yG8FFR2rxZaNHiKQJPQSUsf6etYzwBI5LhAwQBQ86yJ8H0X7y8ptbUl/YG0CymUO1lWyiCoGy4RR/+IrojSX9jpB8t85zczd4mH9/YJ6z8kMmIwJbsNPYgTHRCfeGU0nB+DlfV2AD1gvcE23PSBwUvIKrHLYxcA8kzmsYPqwQnEIObtOr/OeL32kTxkLFHM9k6Vndmy3cbwCBllycWrjOS0hHZAZag/DbYQjJzEkNCiaqZywxl30RNRsJ0TirMQAQGTdfRQr/e1TT2RCMxz7t3fhnkTgyOSmXnclyVGsqI2zMRHyXqtz/Ak7kULm3Ukq98w9HjMBhjmPvf28zLC0MBdYSxWD0vdfZwNAwU/uR+pwh1TztWHX8hJ5PZ+QruLo7vf+5OuMGzBDmb3kcbNI0UCV3GJiiKhO3YJwSVe2OyXAy3O/PVvQS2TCd631ax+faeJsmZk0k3UxzNe+ilFYswz2q3GYO8aLh1NiLy5GzFqR5CJQnKP8YAe+UMsYKLmhxDbEesLvUa5L2l3K1ZMhjSoyQWsOi8VBIwGC5TpHNMiNfsdQm2QcJZPBzHNYABzvsPZDTWWtyTJ0HfD4aDsVDAdX3TnA5H7fBSjjJX6g2L6BenMaq3hxofn/cSKmN9evky7ShQWZhbrvk/WQ=}
