travis:
  secure:
    BINSTAR_TOKEN: NFsZLMf9yhNyxyh8HFpdk8dskCv+dLNWxxBbrHsm8x9q8oLz5miV0IWkmGIlmUQ4BWwJF18E0QEriGhyMkODH3xKQA9cqHSxq0xWXt4J65TF42KjfQUpB2AhTowLY2F4aIJgKozv69gQDDzmCIswDPjjmdNlzcOARuhSDsW4uQjo95YmmT7G5NWl+TCHcR+lz6CxEFtUbdY/pKLBXYDzKvQCfSrP/DG3ee25N2GQ9X5Mr8T/6PxpVIMWCrAY84hect5U/4aW3zfd740X9kfhD4mI5FkQpoDPf2LIK7emza77jIknow6e4fLQdtR4md2WQ1ltYozud2ppaeOtccg6f4tgFcwsRLG20xq893iiJ5bWcDmB2nZzpJQEE1Oi7hlzOI6kOEU7nIht2+d3dO2gU5zbUrO82n9Fb16tHdv4UNZYKIBcoL3xk6JBmxBODYMgdzjgVwlyiTVCvr/4s1uaeZyybzaKvYuob0KEV0bsHOPFjvggbzyZVGC6I167W3zQuBCe38HnTmsBmYaQvDkMQDWqwHShGk8SyMELUEZGdEv4yHiThQYqYvBuN6Y9gBAeH1ZE2saqVDBt7b3f50kjpra0yni/QpuxZZICCuxNyr3LFbgjaTN/R8GqZ+zccrRPvoEnJuz1IAv/MaLQuZv767Qum0sd2lV7A0YF6HR6ctg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
